const lessons = [
  { title: 'Hello, little computer', desc: 'What code is, and why Python is friendly.', quiz: 'Which word means a set of instructions for a computer?', options: ['A program', 'A sandwich', 'A keyboard'], answer: 0 },
  { title: 'Giving things names', desc: 'Meet variables: labeled boxes for your ideas.', quiz: 'What is a variable best like?', options: ['A labeled box', 'A loud noise', 'A web page'], answer: 0 },
  { title: 'Talking to your program', desc: 'Use print() to make your code speak.', quiz: 'Which line says hello in Python?', options: ['print("Hello")', 'say Hello!', 'echo.hello'], answer: 0 },
  { title: 'Your first tiny program', desc: 'Put the pieces together and make a mini story.', quiz: 'What should you do when code feels tricky?', options: ['Try one tiny change', 'Give up forever', 'Delete the computer'], answer: 0 }
];
const seedUser = { name: 'Student', email: '', password: '', completed: [], chats: [], streak: 0, lastVisit: '' };
let user = loadSession();
let authMode = 'signup';
let activeLesson = 0;
let groqKey = '';
const $ = (id) => document.getElementById(id);

function loadSession() { try { return JSON.parse(localStorage.getItem('sproutcode-session')) || null; } catch { return null; } }
function saveUser() { localStorage.setItem('sproutcode-session', JSON.stringify(user)); }
function users() { try { return JSON.parse(localStorage.getItem('sproutcode-users')) || {}; } catch { return {}; } }
function updateUserUI() { if (!user) return; $('profileName').textContent = user.name; $('welcomeName').textContent = user.name.split(' ')[0]; $('avatar').textContent = user.name[0].toUpperCase(); $('streakValue').textContent = `${user.streak || 0} day streak`; const percent = Math.round((user.completed.length / lessons.length) * 100); $('progressPercent').textContent = `${percent}%`; document.querySelector('.progress-ring').style.setProperty('--progress', `${percent}%`); }
function renderLessons() { $('lessonList').innerHTML = lessons.map((lesson, index) => { const done = user?.completed.includes(index); return `<button class="lesson-card ${done ? 'done' : ''} ${activeLesson === index ? 'selected' : ''}" data-lesson="${index}"><span class="lesson-number">${done ? '✓' : `0${index + 1}`}</span><span><h3>${lesson.title}</h3><p>${lesson.desc}</p></span><span class="status">${done ? 'complete' : index === 0 ? 'begin here' : 'next page →'}</span></button>`; }).join(''); document.querySelectorAll('[data-lesson]').forEach((button) => button.addEventListener('click', () => { activeLesson = Number(button.dataset.lesson); openQuiz(activeLesson); })); }
function renderAssignment() { const next = user.completed.length; $('assignmentTitle').textContent = next < lessons.length ? `Practice: ${lessons[next].title}` : 'You grew the whole garden!'; $('assignmentText').textContent = next < lessons.length ? lessons[next].quiz : 'You finished the first Python garden. A new language is waiting to sprout soon.'; $('assignmentButton').innerHTML = next < lessons.length ? 'Take tiny quiz <span>→</span>' : 'Review lessons <span>↗</span>'; }
function openQuiz(index) { activeLesson = index; const lesson = lessons[index]; $('quizTitle').textContent = lesson.title; $('quizPrompt').textContent = lesson.quiz; $('quizResult').textContent = ''; $('quizOptions').innerHTML = lesson.options.map((option, i) => `<button class="quiz-option" data-answer="${i}">${option}</button>`).join(''); $('quizModal').classList.remove('hidden'); document.querySelectorAll('[data-answer]').forEach((button) => button.addEventListener('click', () => answerQuiz(Number(button.dataset.answer), index))); }
function answerQuiz(answer, index) { const buttons = document.querySelectorAll('[data-answer]'); buttons.forEach((button) => { button.disabled = true; if (Number(button.dataset.answer) === lessons[index].answer) button.classList.add('correct'); }); if (answer === lessons[index].answer) { if (!user.completed.includes(index)) user.completed.push(index); user.streak = Math.max(1, user.streak || 0); saveUser(); updateUserUI(); renderLessons(); renderAssignment(); $('quizResult').textContent = 'Yes! Your brain just made a new little path. ✨'; } else { buttons[answer].classList.add('wrong'); $('quizResult').textContent = 'Almost! Take another peek at the lesson and try again.'; setTimeout(() => { buttons.forEach((button) => { button.disabled = false; button.classList.remove('wrong'); }); }, 900); } }
function addChat(text, type) { const bubble = document.createElement('div'); bubble.className = `chat-bubble ${type}-bubble`; bubble.textContent = text; $('chatLog').appendChild(bubble); $('chatLog').scrollTop = $('chatLog').scrollHeight; }
function replyFor(message) { const text = message.toLowerCase(); if (text.includes('variable')) return 'A variable is a labeled box. You can put a value inside it, like: name = "Mina". Later, saying name brings the value back. Easy peasy.'; if (text.includes('python')) return 'Python is a language for giving instructions to computers. People like it because it reads almost like a sentence. We will learn it one small idea at a time.'; if (text.includes('stuck') || text.includes('hard')) return 'Being stuck is part of learning, not a sign you are bad at it. Tell me the exact line that feels wobbly and we’ll untangle just that bit.'; if (text.includes('print')) return 'print() is Python’s little megaphone. Try print("hello, world!") and your computer will show those words.'; return 'That is a lovely question. Let’s make it smaller: what is the one word or part that feels mysterious? I can explain it with a tiny example.'; }
async function replyFromGroq(message) { const response = await fetch('https://api.groq.com/openai/v1/chat/completions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${groqKey}` }, body: JSON.stringify({ model: 'llama-3.1-8b-instant', temperature: 0.4, max_tokens: 180, messages: [{ role: 'system', content: 'You are Sprout, a patient coding tutor for a complete beginner. Explain one idea at a time using gentle toddler-simple language, tiny Python examples, and no jargon unless you define it. When helpful, suggest a tiny practice task. Keep replies under 90 words.' }, { role: 'user', content: message }] }) }); if (!response.ok) throw new Error('Groq request failed'); const data = await response.json(); return data.choices?.[0]?.message?.content || replyFor(message); }
function configureAI() { const key = window.prompt('Paste your Groq API key for this browser session. It will not be saved in the app files or localStorage.'); if (!key?.trim()) return; groqKey = key.trim(); $('aiToggle').textContent = 'Groq AI on'; $('aiToggle').classList.add('connected'); addChat('Groq AI is connected for this session. I’ll still keep explanations gentle and beginner-friendly.', 'tutor'); }
function startApp() { updateUserUI(); renderLessons(); renderAssignment(); const today = new Date().toDateString(); if (user.lastVisit !== today) { user.streak = user.lastVisit ? (new Date(today) - new Date(user.lastVisit) < 172800000 ? (user.streak || 0) + 1 : 1) : 1; user.lastVisit = today; saveUser(); updateUserUI(); } $('authOverlay').classList.add('hidden'); }
$('authForm').addEventListener('submit', (event) => { event.preventDefault(); const name = $('authName').value.trim(); const email = $('authEmail').value.trim().toLowerCase(); const password = $('authPassword').value; const stored = users(); if (authMode === 'signup') { if (stored[email]) { $('authError').textContent = 'That email already has a garden. Try signing in.'; return; } user = { ...seedUser, name, email, password }; stored[email] = user; localStorage.setItem('sproutcode-users', JSON.stringify(stored)); } else { if (!stored[email] || stored[email].password !== password) { $('authError').textContent = 'That email or password did not match.'; return; } user = stored[email]; } saveUser(); startApp(); });
$('authToggle').addEventListener('click', () => { authMode = authMode === 'signup' ? 'signin' : 'signup'; $('authName').parentElement.style.display = authMode === 'signup' ? 'grid' : 'none'; $('authSubmitText').textContent = authMode === 'signup' ? 'Start learning' : 'Open my garden'; $('authToggle').innerHTML = authMode === 'signup' ? 'Already have an account? <strong>Sign in</strong>' : 'New here? <strong>Create an account</strong>'; $('authError').textContent = ''; });
$('chatForm').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('chatInput'); const message = input.value.trim(); if (!message) return; addChat(message, 'user'); input.value = ''; user.chats = [...(user.chats || []), message].slice(-20); saveUser(); if (!groqKey) { setTimeout(() => addChat(replyFor(message), 'tutor'), 220); return; } addChat('Sprout is thinking...', 'tutor'); try { const reply = await replyFromGroq(message); const thinking = [...$('chatLog').querySelectorAll('.tutor-bubble')].find((bubble) => bubble.textContent === 'Sprout is thinking...'); if (thinking) thinking.remove(); addChat(reply, 'tutor'); } catch { addChat('The AI connection took a little wobble, so here is my offline thought instead: ' + replyFor(message), 'tutor'); } });
document.querySelectorAll('[data-prompt]').forEach((button) => button.addEventListener('click', () => { $('chatInput').value = button.dataset.prompt; $('chatForm').requestSubmit(); }));
$('aiToggle').addEventListener('click', configureAI); $('assignmentButton').addEventListener('click', () => openQuiz(Math.min(user.completed.length, lessons.length - 1))); $('closeQuiz').addEventListener('click', () => $('quizModal').classList.add('hidden')); $('quizModal').addEventListener('click', (event) => { if (event.target === $('quizModal')) $('quizModal').classList.add('hidden'); }); $('mobileMenu').addEventListener('click', () => document.querySelector('.sidebar').classList.toggle('open')); $('helpButton').addEventListener('click', () => { addChat('You are doing better than you think. Pick the first lesson, answer the tiny quiz, and let momentum do the rest.', 'tutor'); }); $('themeButton').addEventListener('click', () => document.body.classList.toggle('calm-mode'));
if (user) startApp();